### ISSUE TITLE
Renaming false positive (renaming parameter of one function mistakenly renames parameter of other function)

### ISSUE THREAD

**Issue by Janiczek** [jwoudenberg/elm-pair#21] opened 2022-04-07 14:05 UTC
This isn't a runnable SSCCE but roughly what's happening:

```elm
fun1 ctx = ...
fun2 context = ...
```
:arrow_down: rename `context` in `fun2` to `ctx`
```elm
fun1 ctx2 = ... -- bug
fun2 ctx = ...
```

This is happening on `main` as of `d0b5f29de20a70e009578b7735d8ac8ad9481036`.

Seems like these two parameters are unrelated, so we shouldn't be renaming one when changing the other.

https://user-images.githubusercontent.com/149425/162218763-3410b326-2dbf-41c5-a264-ad7b93acdb64.mp4

**Comment by jwoudenberg** [comment] 2022-04-07 15:41
Looks like maybe a regression I introduced in today's release. I definitely agree the rename shouldn't happen. Thank you for the clear bug report, I'll look into this first thing tomorrow!

**Comment by jwoudenberg** [comment] 2022-04-08 10:42
Fixed in release 16, which is now live!

![rec](https://user-images.githubusercontent.com/1525551/162420085-1d85c49f-6ffe-4126-8f99-4f540a129ae8.gif)

For what it's worth, I don't think this was a regression, and that the problem already existed earlier.

Thank you for letting me know about this bug!

**Closed as completed by jwoudenberg** 2022-04-08 10:42 UTC
Labels: bug

**Comment by Janiczek** [comment] 2022-04-08 10:51
Thanks for being so quick about these fixes, @jwoudenberg !
